###
GET http://localhost:3000



###
PUT http://localhost:3000/example/11/67
App

###
GET  http://localhost:3000/v1/test
content-type: application/json

###
GET http://localhost:3000/v1/test/10
content-type: application/json

###
POST http://localhost:3000/post
content-type: application/json

{
    "name" : "subhadip" ,
    "age" : 20
}


###
GET http://localhost:3000/example?id=10
content-type: application/json


### /v1/test/ok/*
GET http://localhost:3000/v1/test/ok/ok1/ok2/ok3
content-type: application/json