###
GET http://localhost:3000



###
PUT http://localhost:3000/example/11/67
App

###
GET  http://localhost:3000/v1/test
content-type: application/json

###
PUT http://localhost:3000/v1/test/10


###
GET http://localhost:3000/v1/test/ok/hi/01