###
GET http://localhost:8080
content-type: application/json

###
GET http://localhost:8080/v1/test
content-type: application/json

###
GET http://localhost:8090/__stats 


###
GET http://localhost:8090/__stats